name: build
permissions:
  contents: read

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - 'Docs/**'       # Docs folder in root of repo
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  pull_request:
    branches: [main]
    paths-ignore:
      - 'Docs/**'       # Docs folder in root of repo
      - '**/*.md'       # .md files anywhere in the repo
      - '**/LICENSE'    # LICENSE files anywhere in the repo
      - '**/.gitignore' # .gitignore files anywhere in the repo
      
  workflow_dispatch:
    
  schedule:
    - cron: '10 11 * * *'   # once a day @ 11:10am UTC (4:50am PST)

env:
  SCHEME: swift-path
  WORKSPACEPATH: .swiftpm/xcode/package.xcworkspace

jobs:
  macOS:
    name: Tests - Default Traits (macOS)
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: xcodebuild build -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Unit Tests
      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

  macCatalyst:
    name: Tests - All Traits (macCatalyst)
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    # there is no swift command to edit package traits, so manually editing the package manifest is the best interim solution
    - name: Enable All Traits
      run: perl -pi -e 's/\.default\(enabledTraits\: \[\]\)/\.default\(enabledTraits\: \[\"osc\"\]\)/g' Package.swift
    - name: Build
      run: xcodebuild build -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
    - name: Unit Tests
      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}

  device-simulators:
    name: Tests - All Traits
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: [iOS, tvOS, watchOS, visionOS]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Prepare Device Simulator
      id: sim-setup
      uses: orchetect/setup-xcode-simulator@v1
      with:
        refresh: true
        download: true
        scheme: ${{ env.SCHEME }}
        target: ${{ matrix.target }}
    # there is no swift command to edit package traits, so manually editing the package manifest is the best interim solution
    - name: Enable All Traits
      run: perl -pi -e 's/\.default\(enabledTraits\: \[\]\)/\.default\(enabledTraits\: \[\"osc\"\]\)/g' Package.swift
    - name: Build
      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=$PLATFORMSHORT" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
      env:
        PLATFORMSHORT: ${{ steps.sim-setup.outputs.platform-short }}
        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
    - name: Unit Tests
      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=$PLATFORM,id=$ID" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
      env:
        ID: ${{ steps.sim-setup.outputs.id }}
        PLATFORM: ${{ steps.sim-setup.outputs.platform }}
        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}

  linux:
    name: Tests - All Traits (Linux)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: swift build --enable-all-traits
    - name: Unit Tests
      run: swift test --enable-all-traits

  android:
    name: Build - All Traits (Android)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      TARGET_TRIPLE: aarch64-unknown-linux-android28
    steps:
    - uses: actions/checkout@main
    - uses: orchetect/setup-swift-android-sdk@v1
      with:
        target-triple: ${{ env.TARGET_TRIPLE }}
    - name: Build
      run: swift build --enable-all-traits --swift-sdk "$TARGET_TRIPLE" --static-swift-stdlib

  no-traits:
    name: Tests (No Traits)
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: swift build --disable-default-traits
    - name: Unit Tests
      run: swift test --disable-default-traits

  osc-trait:
    name: Tests (OSC Trait)
    runs-on: macos-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: swift build --traits osc
    - name: Unit Tests
      run: swift test --traits osc
